global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#nikolay_ostroushko'
