---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      name: ui-pod
      labels:
        app: ui
    spec:
      containers:
      - image: koxx009/ui
        name: ui
